name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Compress Images
        uses: calibreapp/image-actions@main
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache 
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ".jekyll-cache"
        # An explicit key for restoring and saving the cache
        key: "jekyll-cache"

      